links:
  rails_tutorial:
    home_page: "https://www.railstutorial.org/"
    help_page: "https://www.railstutorial.org/help"
    book_page: "https://www.railstutorial.org/book"
    screencasts_page: "https://screencasts.railstutorial.org/"
    contact_page: https://www.railstutorial.org/contact
    author: https://www.michaelhartl.com/
  learn_enough: "https://www.learnenough.com/"
validation:
  name:
    max_length: 50
  email:
    max_length: 255
    regex: !ruby/regexp '/\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i'
  password:
    min_length: 6
helpers:
  gravatar:
    size: 80
users:
  edit:
    gravatar_link: https://gravatar.com/emails
  index:
    size_gravatar: 50
checkbox: 1
pagination: 10
time:
  expried: 2
micropost:
  content:
    max_length: 140
shared:
  user_info_length: 50
pages:
  limit: 5
files:
  pic_resize: 500
  pic_size: 5
image:
  valid_input: image/jpeg,image/gif,image/png
static_pages:
  home:
    image_size: 200px
